// Task Analyzer - uses AI to analyze conversation and generate tasks

import type { PromptManager } from '@/ai/prompt/PromptManager';
import { PromptMessageAssembler } from '@/ai/prompt/PromptMessageAssembler';
import type { LLMService } from '@/ai/services/LLMService';
import { type ExtractStrategy, extractJsonFromLlmText } from '@/ai/utils/llmJsonExtract';
import type { ConversationContext } from '@/context/types';
import type { ConversationMessageEntry } from '@/conversation/history';
import { logger } from '@/utils/logger';
import type { TaskManager } from './TaskManager';
import type { Task, TaskAnalysisResult, TaskType } from './types';

/**
 * Task Analyzer - analyzes conversation using AI and generates tasks
 */
export class TaskAnalyzer {
  private messageAssembler = new PromptMessageAssembler();
  /**
   * Parse AI response to extract task list.
   * Tries ANSWER:, code block, brace-balanced (reasoning models), single-line, regex.
   */
  private static readonly TASK_JSON_EXTRACT_STRATEGIES: ExtractStrategy[] = [
    'answer',
    'codeBlock',
    'braceMatch',
    'line',
    'regex',
  ];

  constructor(
    private llmService: LLMService,
    private taskManager: TaskManager,
    private promptManager: PromptManager,
  ) {}

  /**
   * Analyze conversation and generate tasks.
   * Returns multiple tasks (excluding reply task which is always generated by system).
   */
  async analyze(context: ConversationContext): Promise<TaskAnalysisResult> {
    const messages = this.buildMessages(context);
    const response = await this.llmService.generateMessages(messages, {
      temperature: 0.3,
      maxTokens: 1000,
      includeReasoning: false, // Don't include reasoning in response text, extract JSON from content
    });

    // Parse AI response to extract task list + optional provider suggestion
    const parsedResult = this.parseTaskListResponse(response.text, context);
    const tasks = parsedResult.tasks;

    logger.info(
      `[TaskAnalyzer] ✓ Task analysis completed | taskCount=${tasks.length} | tasks=${tasks.map((t) => t.type).join(', ')} | suggestedProvider=${parsedResult.suggestedProvider ?? 'none'}`,
    );

    return {
      tasks,
      suggestedProvider: parsedResult.suggestedProvider,
      confidence: 0.8, // Default confidence, can be improved with better parsing
    };
  }

  /**
   * Build system+user prompts for AI task analysis.
   */
  private buildMessages(context: ConversationContext) {
    // Build task types description with enhanced information(excluding reply task type)
    const taskTypes = this.taskManager.getAllTaskTypes().filter((tt) => tt.name.toLowerCase() !== 'reply');

    const taskTypesDescription = taskTypes
      .map((tt) => {
        let desc = `- ${tt.name}: ${tt.description}`;

        // Add executor information
        desc += `\n  执行器: ${tt.executor}`;

        // Add when to use guidance if available
        if (tt.whenToUse) {
          desc += `\n  使用场景: ${tt.whenToUse}`;
        }

        // Add trigger keywords if available
        if (tt.triggerKeywords && tt.triggerKeywords.length > 0) {
          desc += `\n  触发关键词: ${tt.triggerKeywords.join(', ')}`;
        }

        // Add examples if available
        if (tt.examples && tt.examples.length > 0) {
          desc += `\n  示例消息:\n${tt.examples.map((ex) => `    - "${ex}"`).join('\n')}`;
        }

        // Add parameters if available
        if (tt.parameters) {
          const params = Object.entries(tt.parameters)
            .map(([key, def]) => `    - ${key} (${def.type}, ${def.required ? '必填' : '可选'}): ${def.description}`)
            .join('\n');
          desc += `\n  参数:\n${params}`;
        }

        return desc;
      })
      .join('\n\n');

    // Base prompt should be system role.
    const basePrompt = this.promptManager.renderBasePrompt();
    const sceneSystemPrompt = this.promptManager.render('task.analyze.system', { taskTypesDescription });
    const currentQueryPrompt = this.promptManager.render('task.analyze.user_frame', {
      userMessage: context.userMessage,
    });
    const historyEntries: ConversationMessageEntry[] = (context.history ?? []).map((msg, i) => ({
      messageId: `ctx:${i}`,
      userId: msg.role === 'assistant' ? 0 : context.userId,
      nickname: undefined,
      content: msg.content,
      isBotReply: msg.role === 'assistant',
      createdAt: msg.timestamp instanceof Date ? msg.timestamp : new Date(msg.timestamp),
      segments: undefined,
    }));
    const messages = this.messageAssembler.buildTaskAnalyzeMessages({
      baseSystem: basePrompt,
      sceneSystem: sceneSystemPrompt,
      historyEntries,
      currentQuery: currentQueryPrompt,
    });
    logger.debug(`[TaskAnalyzer] Prompts built | messageCount=${messages.length}`);
    return messages;
  }

  private parseTaskListResponse(aiResponse: string, context: ConversationContext): TaskAnalysisResult {
    const jsonText = extractJsonFromLlmText(aiResponse, {
      strategies: TaskAnalyzer.TASK_JSON_EXTRACT_STRATEGIES,
    });
    if (!jsonText) {
      return { tasks: [] };
    }

    let parsed: { tasks: Task[]; suggestedProvider?: unknown };
    try {
      parsed = JSON.parse(jsonText) as { tasks: Task[]; suggestedProvider?: unknown };
    } catch (parseError) {
      const errorMsg = parseError instanceof Error ? parseError.message : 'Unknown error';
      logger.error(`[TaskAnalyzer] ✗ Failed to parse JSON: ${errorMsg}`);
      return { tasks: [] };
    }

    if (!parsed.tasks || !Array.isArray(parsed.tasks)) {
      logger.error(`[TaskAnalyzer] ✗ Invalid JSON format: expected {"tasks": [...]}, got: ${JSON.stringify(parsed)}`);
      return { tasks: [] };
    }

    const taskList = parsed.tasks;

    // Convert to Task objects, validate task type exists
    const validTasks: Task[] = [];
    for (const t of taskList) {
      if (!t.type) {
        continue;
      }
      const taskTypeDef = this.taskManager.getTaskType(t.type);
      if (!taskTypeDef) {
        continue;
      }
      // Validate parameters (if task type defines parameters)
      if (taskTypeDef.parameters) {
        // Basic validation: check required parameters
        for (const [key, def] of Object.entries(taskTypeDef.parameters)) {
          if (def.required && !(key in (t.parameters || {}))) {
            logger.warn(`[TaskAnalyzer] Missing required parameter: ${key} for task type: ${taskTypeDef.name}`);
          }
        }
      }
      try {
        validTasks.push(this.parseSingleTask(taskTypeDef, t.parameters || {}, context));
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error';
        logger.warn(`[TaskAnalyzer] Failed to parse task ${t.type}: ${errorMsg}`);
      }
    }

    return {
      tasks: validTasks,
      suggestedProvider: this.normalizeSuggestedProvider(parsed.suggestedProvider),
    };
  }

  private normalizeSuggestedProvider(provider: unknown): string | undefined {
    if (typeof provider !== 'string') {
      return undefined;
    }
    const normalized = provider.trim().toLowerCase();
    return normalized.length > 0 ? normalized : undefined;
  }

  /**
   * Parse single task from parsed JSON object
   */
  private parseSingleTask(taskType: TaskType, parameters: Record<string, unknown>, context: ConversationContext): Task {
    return {
      type: taskType.name,
      parameters: parameters, // Use actual parameters from AI response
      executor: taskType.executor, // Use executor defined in task type
      metadata: {
        analyzedAt: new Date().toISOString(),
        userId: context.userId,
        groupId: context.groupId,
      },
    };
  }
}
