// Task Analyzer - uses AI to analyze conversation and generate tasks

import type { PromptManager } from '@/ai/prompt/PromptManager';
import type { LLMService } from '@/ai/services/LLMService';
import { type ExtractStrategy, extractJsonFromLlmText } from '@/ai/utils/llmJsonExtract';
import type { ConversationContext } from '@/context/types';
import { logger } from '@/utils/logger';
import type { TaskManager } from './TaskManager';
import type { Task, TaskAnalysisResult, TaskType } from './types';

/**
 * Task Analyzer - analyzes conversation using AI and generates tasks
 */
export class TaskAnalyzer {
  /**
   * Parse AI response to extract task list.
   * Tries ANSWER:, code block, brace-balanced (reasoning models), single-line, regex.
   */
  private static readonly TASK_JSON_EXTRACT_STRATEGIES: ExtractStrategy[] = [
    'answer',
    'codeBlock',
    'braceMatch',
    'line',
    'regex',
  ];

  constructor(
    private llmService: LLMService,
    private taskManager: TaskManager,
    private promptManager: PromptManager,
  ) {}

  /**
   * Analyze conversation and generate tasks
   * Returns multiple tasks (excluding reply task which is always generated by system)
   * Returns empty array if parsing fails (upstream should ensure valid JSON output)
   * @param options.injectBase - When true, prepend base prompt to system template (e.g. for pipeline use)
   */
  async analyze(context: ConversationContext, options?: { injectBase?: boolean }): Promise<TaskAnalysisResult> {
    // Build prompt for AI
    const prompt = this.buildPrompt(context, options);

    const response = await this.llmService.generate(prompt, {
      temperature: 0.4,
      maxTokens: 1000,
      includeReasoning: false, // Don't include reasoning in response text, extract JSON from content
    });

    // Parse AI response to extract task list
    const tasks = this.parseTaskListResponse(response.text, context);

    logger.info(
      `[TaskAnalyzer] ✓ Task analysis completed | taskCount=${tasks.length} | tasks=${tasks.map((t) => t.type).join(', ')}`,
    );

    return {
      tasks,
      confidence: 0.8, // Default confidence, can be improved with better parsing
    };
  }

  /**
   * Build prompt for AI task analysis
   * Uses PromptManager to render separate system and user templates
   * All prompt content is managed through templates, no hardcoded prompts
   */
  private buildPrompt(context: ConversationContext, options?: { injectBase?: boolean }): string {
    // Build task types description with enhanced information(excluding reply task type)
    const taskTypes = this.taskManager.getAllTaskTypes().filter((tt) => tt.name.toLowerCase() !== 'reply');

    const taskTypesDescription = taskTypes
      .map((tt) => {
        let desc = `- ${tt.name}: ${tt.description}`;

        // Add executor information
        desc += `\n  执行器: ${tt.executor}`;

        // Add when to use guidance if available
        if (tt.whenToUse) {
          desc += `\n  使用场景: ${tt.whenToUse}`;
        }

        // Add trigger keywords if available
        if (tt.triggerKeywords && tt.triggerKeywords.length > 0) {
          desc += `\n  触发关键词: ${tt.triggerKeywords.join(', ')}`;
        }

        // Add examples if available
        if (tt.examples && tt.examples.length > 0) {
          desc += `\n  示例消息:\n${tt.examples.map((ex) => `    - "${ex}"`).join('\n')}`;
        }

        // Add parameters if available
        if (tt.parameters) {
          const params = Object.entries(tt.parameters)
            .map(([key, def]) => `    - ${key} (${def.type}, ${def.required ? '必填' : '可选'}): ${def.description}`)
            .join('\n');
          desc += `\n  参数:\n${params}`;
        }

        return desc;
      })
      .join('\n\n');

    // Build conversation history text
    const historyText = context.history
      ? context.history.map((msg) => `${msg.role === 'user' ? '用户' : '助手'}: ${msg.content}`).join('\n')
      : '无对话历史。';

    // Render system prompt template
    const systemPrompt = this.promptManager.render(
      'task.analyze.system',
      { taskTypesDescription },
      options?.injectBase ? { injectBase: true } : undefined,
    );

    // Render user prompt template
    const userPrompt = this.promptManager.render('task.analyze.user', {
      conversationHistory: historyText,
      userMessage: context.userMessage,
    });

    // Combine system and user prompts
    const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;

    logger.debug(`[TaskAnalyzer] Prompt built | fullPromptLength=${fullPrompt.length}`);

    return fullPrompt;
  }

  private parseTaskListResponse(aiResponse: string, context: ConversationContext): Task[] {
    const jsonText = extractJsonFromLlmText(aiResponse, {
      strategies: TaskAnalyzer.TASK_JSON_EXTRACT_STRATEGIES,
    });
    if (!jsonText) {
      return [];
    }

    let parsed: { tasks: Task[] };
    try {
      parsed = JSON.parse(jsonText) as { tasks: Task[] };
    } catch (parseError) {
      const errorMsg = parseError instanceof Error ? parseError.message : 'Unknown error';
      logger.error(`[TaskAnalyzer] ✗ Failed to parse JSON: ${errorMsg}`);
      return [];
    }

    if (!parsed.tasks || !Array.isArray(parsed.tasks)) {
      logger.error(`[TaskAnalyzer] ✗ Invalid JSON format: expected {"tasks": [...]}, got: ${JSON.stringify(parsed)}`);
      return [];
    }

    const taskList = parsed.tasks;

    // Convert to Task objects, validate task type exists
    const validTasks: Task[] = [];
    for (const t of taskList) {
      if (!t.type) {
        continue;
      }
      const taskTypeDef = this.taskManager.getTaskType(t.type);
      if (!taskTypeDef) {
        continue;
      }
      // Validate parameters (if task type defines parameters)
      if (taskTypeDef.parameters) {
        // Basic validation: check required parameters
        for (const [key, def] of Object.entries(taskTypeDef.parameters)) {
          if (def.required && !(key in (t.parameters || {}))) {
            logger.warn(`[TaskAnalyzer] Missing required parameter: ${key} for task type: ${taskTypeDef.name}`);
          }
        }
      }
      try {
        validTasks.push(this.parseSingleTask(taskTypeDef, t.parameters || {}, context));
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error';
        logger.warn(`[TaskAnalyzer] Failed to parse task ${t.type}: ${errorMsg}`);
      }
    }

    return validTasks;
  }

  /**
   * Parse single task from parsed JSON object
   */
  private parseSingleTask(taskType: TaskType, parameters: Record<string, unknown>, context: ConversationContext): Task {
    return {
      type: taskType.name,
      parameters: parameters, // Use actual parameters from AI response
      executor: taskType.executor, // Use executor defined in task type
      metadata: {
        analyzedAt: new Date().toISOString(),
        userId: context.userId,
        groupId: context.groupId,
      },
    };
  }
}
