// Task type definitions

/**
 * Task type definition
 * Defines a task type with clear description, examples, and trigger conditions
 */
export interface TaskType {
  /**
   * Task type name (unique identifier)
   */
  name: string;

  /**
   * Task description - what this task does
   */
  description: string;

  /**
   * Executor identifier - "reply" | "plugin:xxx" | "builtin:xxx"
   */
  executor: string;

  /**
   * Task parameters definition
   */
  parameters?: {
    [key: string]: {
      type: string;
      required: boolean;
      description: string;
    };
  };

  /**
   * Example user messages that would trigger this task type
   * Helps AI understand when to use this task type
   */
  examples?: string[];

  /**
   * Trigger conditions or keywords that indicate this task type
   * Optional: helps AI identify when to use this task
   */
  triggerKeywords?: string[];

  /**
   * When to use this task type (detailed guidance for AI)
   */
  whenToUse?: string;
}

/**
 * Task object generated by AI or manually
 */
export interface Task {
  id?: string;
  type: string; // Task type name
  parameters: Record<string, unknown>;
  reply?: string; // Optional AI-generated reply
  executor: string;
  priority?: number;
  metadata?: Record<string, unknown>;
}

/**
 * Task execution result
 */
export interface TaskResult {
  success: boolean;
  reply: string; // Reply message (required)
  data?: Record<string, unknown>; // Additional execution data
  error?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Task executor interface
 */
export interface TaskExecutor {
  /**
   * Executor identifier
   */
  name: string;

  /**
   * Execute task
   */
  execute(task: Task, context: TaskExecutionContext): Promise<TaskResult> | TaskResult;
}

/**
 * Task execution context
 */
export interface TaskExecutionContext {
  userId: number;
  groupId?: number;
  messageType: 'private' | 'group';
  conversationId?: string;
  messageId?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Task analysis result
 */
export interface TaskAnalysisResult {
  tasks: Task[];
  confidence?: number;
  reasoning?: string;
}
