// Task type definitions

/**
 * Task type definition
 */
export interface TaskType {
  name: string;
  description: string;
  executor: string; // "reply" | "plugin:xxx" | "builtin:xxx"
  parameters?: {
    [key: string]: {
      type: string;
      required: boolean;
      description: string;
    };
  };
}

/**
 * Task object generated by AI or manually
 */
export interface Task {
  id?: string;
  type: string; // Task type name
  parameters: Record<string, unknown>;
  reply?: string; // Optional AI-generated reply
  executor: string;
  priority?: number;
  metadata?: Record<string, unknown>;
}

/**
 * Task execution result
 */
export interface TaskResult {
  success: boolean;
  reply: string; // Reply message (required)
  data?: Record<string, unknown>; // Additional execution data
  error?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Task executor interface
 */
export interface TaskExecutor {
  /**
   * Executor identifier
   */
  name: string;

  /**
   * Execute task
   */
  execute(task: Task, context: TaskExecutionContext): Promise<TaskResult> | TaskResult;
}

/**
 * Task execution context
 */
export interface TaskExecutionContext {
  userId: number;
  groupId?: number;
  messageType: 'private' | 'group';
  conversationId?: string;
  messageId?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Conversation context for task analysis
 */
export interface ConversationContext {
  userMessage: string;
  conversationHistory?: Array<{
    role: 'user' | 'assistant';
    content: string;
  }>;
  userId: number;
  groupId?: number;
  messageType: 'private' | 'group';
}

/**
 * Task analysis result
 */
export interface TaskAnalysisResult {
  task: Task;
  confidence?: number;
  reasoning?: string;
}
