// Dependency injection tokens
// Centralized token management for dependency injection

export const DITokens = {
  COMMAND_MANAGER: 'CommandManager',
  HOOK_MANAGER: 'HookManager',
  TASK_MANAGER: 'TaskManager',
  TASK_SYSTEM: 'TaskSystem',
  AI_MANAGER: 'AIManager',
  AI_SERVICE: 'AIService',
  CONTEXT_MANAGER: 'ContextManager',
  DATABASE_MANAGER: 'DatabaseManager',
  API_CLIENT: 'APIClient',
  CONFIG: 'Config',
  PROMPT_MANAGER: 'PromptManager',
  LLM_SERVICE: 'LLMService',
  PLUGIN_MANAGER: 'PluginManager',
  EVENT_ROUTER: 'EventRouter',
  CONVERSATION_CONFIG_SERVICE: 'ConversationConfigService',
  GLOBAL_CONFIG_MANAGER: 'GlobalConfigManager',
  RETRIEVAL_SERVICE: 'RetrievalService',
  HEALTH_CHECK_MANAGER: 'HealthCheckManager',
  THREAD_SERVICE: 'ThreadService',
  PROACTIVE_CONVERSATION_SERVICE: 'ProactiveConversationService',
  MESSAGE_API: 'MessageAPI',
  SUMMARIZE_SERVICE: 'SummarizeService',
  CONVERSATION_HISTORY_SERVICE: 'ConversationHistoryService',
  PRELIMINARY_ANALYSIS_SERVICE: 'PreliminaryAnalysisService',
  PREFERENCE_KNOWLEDGE_SERVICE: 'PreferenceKnowledgeService',
  PROACTIVE_THREAD_PERSISTENCE_SERVICE: 'ProactiveThreadPersistenceService',
  THREAD_CONTEXT_COMPRESSION_SERVICE: 'ThreadContextCompressionService',
  MEMORY_SERVICE: 'MemoryService',
  MEMORY_EXTRACT_SERVICE: 'MemoryExtractService',
  FILE_READ_SERVICE: 'FileReadService',
  PROCESS_STAGE_INTERCEPTOR_REGISTRY: 'ProcessStageInterceptorRegistry',
  CONVERSATION_MANAGER: 'ConversationManager',
  // Agenda framework (proactive action)
  AGENDA_SERVICE: 'AgendaService',
  AGENT_LOOP: 'AgentLoop',
  INTERNAL_EVENT_BUS: 'InternalEventBus',
  AGENDA_REPORTER: 'AgendaReporter',
  SCHEDULE_FILE_SERVICE: 'ScheduleFileService',
} as const;

export type DIToken = (typeof DITokens)[keyof typeof DITokens];
