// Reply task executor - handles simple reply tasks

import type { TaskExecutor, Task, TaskResult, TaskExecutionContext } from '../types';
import { logger } from '@/utils/logger';

/**
 * Reply task executor
 * Simply returns the reply from the task (usually generated by AI)
 */
export class ReplyTaskExecutor implements TaskExecutor {
  name = 'reply';

  execute(task: Task, context: TaskExecutionContext): TaskResult {
    logger.debug('[ReplyTaskExecutor] Executing reply task');

    // Use reply from task if available
    if (task.reply) {
      return {
        success: true,
        reply: task.reply,
        metadata: task.metadata,
      };
    }

    // Fallback: return a default message
    return {
      success: true,
      reply: 'Task completed',
      metadata: task.metadata,
    };
  }
}
